[project]
name = "azulero"
version = "2.0"
authors = [
  {name="Basset, Antoine", email = "antoine.basset@cnes.fr"},
  {name="Schirmer, Mischa"},
  {name="Bouvard, Téo"},
  {name="Gimenez, Rollin"},
  {name="Nguyen-Kim, Kane"},
  {name="Candini, Gian Paolo"},
  {name="Malapert, Jean-Christophe"}
]
description = "Bring colors to Euclid tiles!"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "Apache-2.0"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "numpy >= 2.0",
    "astropy",
    "astroquery",
    "matplotlib", # FIXME make optional
    "opencv-python",
    "py4j",
    "pyyaml",
    "requests",
    "scikit-image",
    "scipy",
    "shapely"
]

[dependency-groups]
dev = [
  "pytest",
  "sphinx",
  "sphinx-prompt",
  "sphinx-copybutton",
  "sphinxcontrib-mermaid",
  "sphinx-multiversion",
  "sphinx-subfigure"
]

[project.urls]
homepage = "https://doi.org/10.24400/815952/Azulero"

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"

[project.scripts]
azul = "azulero.client:run"
